export const APP_STYLE_CONSTANTS = {
  APP_MAIN_CONTAINER_BG_COLOR: 'rgba(0,0,0,0.5)',
  CARD_DEFAULT_COLOR: '#39a3f4',
  CARD_FLIPPED_COLOR: 'white',
  TEXT_CARD_DEFAULT_COLOR: 'white',
  TEXT_CARD_FLIPPED_COLOR: 'black',
  CARD_BORDER_COLOR: 'white',
};
